language:
- python
python:
- '2.7'
install:
- bash .travis/install.sh
script:
- bash .travis/test.sh
before_deploy: cd nextbus_alexa
deploy:
- provider: lambda
  function_name: alexa-nextbus-dev
  region: us-east-1
  role: arn:aws:iam::251236465048:role/service-role/alexa-wmata
  runtime: python2.7
  module_name: nextbus
  handler_name: lambda_handler
  access_key_id: AKIAJ77MISS2AXMDZ65A
  secret_access_key:
    secure: bydgM1Sz/vgq8EjgeiYSPyp0LsMWzWkQk4hBcEQVRK1HTjKMD4RPqOApw87Hy3wP21CokSS5QFlKNLp7yxbq6txr0XuDVKSgM0WsFun2mWOlshuGusQfn4EEBPV3rU7rErlUVecRY0+wO2KDMeqDLEKs1DslA99eyUz4KwtDdqHF9IDRUtNqPYBiEArMQvfebq+qLIqbbY3B7+i1y4bAKmIAl/WVYMDwI0czJFQabZcy9Xgj66oYOXhT2UPNUwN53w5ua7C2G7dbpf19gHHByrhDw0Xok8guCoMcivVz85QVMM1XH+ZJsGKpb6g4AYPpB3wUo7491gOVclbRdAZDGZj8xa5DzS0SalL2F6WoTK82B1FPjVT8l45HZWNdnD2e/4yzEPwJIohkaXoVZgyILae1073tjia3FLgu4V13ltKJyVmZtpGk5vq/lZVB5ry92wcg116v6Fhj0d7H1DLmXevegZ0jLJzNk7HeOAz6qXCn+4JaEP1V1RfgMsfG3kb669QmoQ3Yf/9KwDowF1nRCsfKotDzULEmFoFZsTGy7GNWwo7JtEuz4eLDIfIL1KFEqFSaXpqBlsYLbL2RJXXqhn5i7fRuOXQlpqtI46MaLYANj+7f+ljTwNCZ0WwHKYWFQCPSAu3l4uUMf8j+oLCzZ8P26MX5r1Ndp/Wc/ABh8Z4=
  on:
    branch: develop
- provider: lambda
  function_name: alexa-nextbus-prod
  region: us-east-1
  role: arn:aws:iam::251236465048:role/service-role/alexa-wmata
  runtime: python2.7
  module_name: nextbus
  handler_name: lambda_handler
  access_key_id: AKIAJ77MISS2AXMDZ65A
  secret_access_key:
    secure: bydgM1Sz/vgq8EjgeiYSPyp0LsMWzWkQk4hBcEQVRK1HTjKMD4RPqOApw87Hy3wP21CokSS5QFlKNLp7yxbq6txr0XuDVKSgM0WsFun2mWOlshuGusQfn4EEBPV3rU7rErlUVecRY0+wO2KDMeqDLEKs1DslA99eyUz4KwtDdqHF9IDRUtNqPYBiEArMQvfebq+qLIqbbY3B7+i1y4bAKmIAl/WVYMDwI0czJFQabZcy9Xgj66oYOXhT2UPNUwN53w5ua7C2G7dbpf19gHHByrhDw0Xok8guCoMcivVz85QVMM1XH+ZJsGKpb6g4AYPpB3wUo7491gOVclbRdAZDGZj8xa5DzS0SalL2F6WoTK82B1FPjVT8l45HZWNdnD2e/4yzEPwJIohkaXoVZgyILae1073tjia3FLgu4V13ltKJyVmZtpGk5vq/lZVB5ry92wcg116v6Fhj0d7H1DLmXevegZ0jLJzNk7HeOAz6qXCn+4JaEP1V1RfgMsfG3kb669QmoQ3Yf/9KwDowF1nRCsfKotDzULEmFoFZsTGy7GNWwo7JtEuz4eLDIfIL1KFEqFSaXpqBlsYLbL2RJXXqhn5i7fRuOXQlpqtI46MaLYANj+7f+ljTwNCZ0WwHKYWFQCPSAu3l4uUMf8j+oLCzZ8P26MX5r1Ndp/Wc/ABh8Z4=
  on:
    branch: master
