language:
- python
python:
- '2.7'
install: ignore
script: ignore
before_deploy: cd nextbus_alexa
deploy:
- provider: lambda
  function_name: alexa-nextbus-dev
  region: us-east-1
  role: arn:aws:iam::251236465048:role/service-role/alexa-wmata
  runtime: python2.7
  module_name: nextbus
  handler_name: lambda_handler
  access_key_id: AKIAJ4RQKULZGZW6W6ZQ
  secret_access_key:
    secure: dNcskkQB4IkuGAMkPltgZgA7OKPZaha5l5t91xRA8IjHzafqH42F/AYa6PRb2yCdvL8zSq11yHmMcoLSiivrjgCwCn+BlmWvHBdhoTeJv9yNKGkrQuCyt8HS+j4bMeMyz55RPnoddEQvx2+ohKMCo9XBfD/bSBgobUy6VRI660GM9A4TjkfLNx5nH5+s5mBbyCXucQutmKhxQqSLWK1FYVCxlnH30Vin2ChjMXrAHSgR6RKn9JSYsl/2bAT7tJiMJyPrCHJWwxV45zQtBtVyyuYRw+8QPr3JuWP4JINTIOTFiuDuyy0or2kjCA+R3Tf1yRzofLrbIm+unjPRaEFw4VRSSUlDAABTScPEwucMYq9b2mLkamm9jLrMAFTmQA+jmc0gkvAO1EU+CZ4gorTlqlEQX63wPBjXVRYcndisOW0Y0UaqYyTvU1ZYENXzgK7T5TMiHUqOjmrTIiFNTz3X3MXeA1AxI3itoEA4qxGpaPnXqRM3/kcoMfgoaCCPQNe5CXo7g4wCnlHuZ8LDoorrXYo+f7EkD7XghX5uWdA2Fm1l5R/9iHnrzxXnhOW9AsQv6cA1wo/v8VWXNmnQBD9MYnTLMkBNYjgCvLCw79DcE6bHkvGJ7g/6EEbUBOjY0Bw05IuosWCkeCqTTw9X6zjgCPN2J822VJwv2gs/ichQ6nw=
  on:
    branch: develop
- provider: lambda
  function_name: alexa-nextbus-prod
  region: us-east-1
  role: arn:aws:iam::251236465048:role/service-role/alexa-wmata
  runtime: python2.7
  module_name: nextbus
  handler_name: lambda_handler
  access_key_id: AKIAJ4RQKULZGZW6W6ZQ
  secret_access_key:
    secure: dNcskkQB4IkuGAMkPltgZgA7OKPZaha5l5t91xRA8IjHzafqH42F/AYa6PRb2yCdvL8zSq11yHmMcoLSiivrjgCwCn+BlmWvHBdhoTeJv9yNKGkrQuCyt8HS+j4bMeMyz55RPnoddEQvx2+ohKMCo9XBfD/bSBgobUy6VRI660GM9A4TjkfLNx5nH5+s5mBbyCXucQutmKhxQqSLWK1FYVCxlnH30Vin2ChjMXrAHSgR6RKn9JSYsl/2bAT7tJiMJyPrCHJWwxV45zQtBtVyyuYRw+8QPr3JuWP4JINTIOTFiuDuyy0or2kjCA+R3Tf1yRzofLrbIm+unjPRaEFw4VRSSUlDAABTScPEwucMYq9b2mLkamm9jLrMAFTmQA+jmc0gkvAO1EU+CZ4gorTlqlEQX63wPBjXVRYcndisOW0Y0UaqYyTvU1ZYENXzgK7T5TMiHUqOjmrTIiFNTz3X3MXeA1AxI3itoEA4qxGpaPnXqRM3/kcoMfgoaCCPQNe5CXo7g4wCnlHuZ8LDoorrXYo+f7EkD7XghX5uWdA2Fm1l5R/9iHnrzxXnhOW9AsQv6cA1wo/v8VWXNmnQBD9MYnTLMkBNYjgCvLCw79DcE6bHkvGJ7g/6EEbUBOjY0Bw05IuosWCkeCqTTw9X6zjgCPN2J822VJwv2gs/ichQ6nw=
  on:
    branch: master
notifications:
  slack:
    rooms:
      secure: csIBATyLXYcJ18CNlhlKM+SX0G62aggsmDiA07hOxEpvcwDSGZeAi0SUqbKWZthB8re0ePWjG3V1m2EMbgWE3bZ4FHeQEFwjV5Md6rgtsA8EmOCsuCkPOOAZQCbz4rjqfIgX5Pdo4aL4aB0XEpQuXG3XvIrK+vmXRVmQHh41bT/WbzieTjIP6I/e1+d6MXNCc5ElOtDKGKuf1zUE4zPI4kLeim3y8NTayWR6clYgoWhhnyDwi/6zBNBUi+8tNf7df8cDnmVEBKxPSbHYDdXCnsasniCr1rgvIyCnniOeDTys0Gv+mtRz/oGT3Mn382EIbWwIFybQa7K16u66viiELAq49s64AruZVDQIP9d15IxrlFNjpLgKKdjPNBHkLv+Dqek7Zx5ijLW0TS7wCaJ85uQuxVuxXzJ20CO4Sb7+8pzlY8kcxLaklazBJtXOaVt/F9D/ozOTd7RodeFMynb8r7DI4wKQu4k0yajD4l5rhaC8No9j36An3+AtHs7KSoqW8mhR0isJ7QFQ4tw51YigR/wivXoDirGr/B4PA9QLzpw8PbJSLi3I96gLE9QMUrqn+36e9E9E3SnDZog3u2GTfLU9PYSU67m4UrV4dgTK7EItLJf2iBes6PxqQIcLTlI58drwAEhFHSt+q3xpgNN6GTdNr2Y6S4AtsNoiv62BJIE=
