language:
- python
python:
- '2.7'
install: ignore
script: ignore
before_deploy: cd nextbus_alexa
deploy:
- provider: lambda
  function_name: alexa-nextbus-dev
  region: us-east-1
  role: arn:aws:iam::251236465048:role/service-role/alexa-wmata
  runtime: python2.7
  module_name: nextbus
  handler_name: lambda_handler
  access_key_id: AKIAIDOGIQUECQ5CMNPQ
  secret_access_key:
    secure: fGdTJHk7vBBUSZtC6OACYqFnFu1Yv0KQOXcCV8vnUNmU5I0tAF/OMejq2H17WDrqSDcUjDJ0Ql0qAVHRR6Bq3dBBqZj+qXwKimIduPBeCPhm0QaIYytV5Qfz3GykY7Pz4UGnWgw7DVXioU1UIO97pLZYDXh7BfrUk68RNxTdBcPhdl57jcV6pMAPXMdpSywKZzDF32H9n5wBdWB67dzY/h4ool779tPhttQpAq/yBmflGh1bmgpyefYi/dM8M/8E2jiURPyyd49zlVmhvf3muzHC/mNlB/r3Cq/PiR5Cd2Bp+j0+cCK5XoOvD7ojPX/6Coy64jx55YFrs3aMlVQgDY4me36eYTpabBaRMokmZ0MUNi1ag4wzgEvSOudaR1Dj7PgYiJbE0rDFcGcnn8JpgXZd0ixM2mtoba11x+p35LTydNDBOxfwVgtqsM69ytwuONtdi9lePWN54wNad8UCPFcWRF9VkjUW7dWpboTrKsHac+yjAu0HwxvuMAuMk+84zFF2Gjv+FZEzrn3WvMTI1Zkd6F5FZARmPuGRL1T2KkIMPJcNGIcsfvXwmUtscAXJZxbfhfFJaUvjcUQGwuj6gXJLyJ4Jbhn34VLtnw9GxRJI5sy17GxJHK6+/E2mlgWcEqwMyq/7bM+H6UTVP++b8rjLh4bqPCyArzyMrawOSTE=
  on:
    branch: develop
- provider: lambda
  function_name: alexa-nextbus-prod
  region: us-east-1
  role: arn:aws:iam::251236465048:role/service-role/alexa-wmata
  runtime: python2.7
  module_name: nextbus
  handler_name: lambda_handler
  access_key_id: AKIAIDOGIQUECQ5CMNPQ
  secret_access_key:
    secure: fGdTJHk7vBBUSZtC6OACYqFnFu1Yv0KQOXcCV8vnUNmU5I0tAF/OMejq2H17WDrqSDcUjDJ0Ql0qAVHRR6Bq3dBBqZj+qXwKimIduPBeCPhm0QaIYytV5Qfz3GykY7Pz4UGnWgw7DVXioU1UIO97pLZYDXh7BfrUk68RNxTdBcPhdl57jcV6pMAPXMdpSywKZzDF32H9n5wBdWB67dzY/h4ool779tPhttQpAq/yBmflGh1bmgpyefYi/dM8M/8E2jiURPyyd49zlVmhvf3muzHC/mNlB/r3Cq/PiR5Cd2Bp+j0+cCK5XoOvD7ojPX/6Coy64jx55YFrs3aMlVQgDY4me36eYTpabBaRMokmZ0MUNi1ag4wzgEvSOudaR1Dj7PgYiJbE0rDFcGcnn8JpgXZd0ixM2mtoba11x+p35LTydNDBOxfwVgtqsM69ytwuONtdi9lePWN54wNad8UCPFcWRF9VkjUW7dWpboTrKsHac+yjAu0HwxvuMAuMk+84zFF2Gjv+FZEzrn3WvMTI1Zkd6F5FZARmPuGRL1T2KkIMPJcNGIcsfvXwmUtscAXJZxbfhfFJaUvjcUQGwuj6gXJLyJ4Jbhn34VLtnw9GxRJI5sy17GxJHK6+/E2mlgWcEqwMyq/7bM+H6UTVP++b8rjLh4bqPCyArzyMrawOSTE=
  on:
    branch: master
notifications:
  slack:
    rooms:
      secure: csIBATyLXYcJ18CNlhlKM+SX0G62aggsmDiA07hOxEpvcwDSGZeAi0SUqbKWZthB8re0ePWjG3V1m2EMbgWE3bZ4FHeQEFwjV5Md6rgtsA8EmOCsuCkPOOAZQCbz4rjqfIgX5Pdo4aL4aB0XEpQuXG3XvIrK+vmXRVmQHh41bT/WbzieTjIP6I/e1+d6MXNCc5ElOtDKGKuf1zUE4zPI4kLeim3y8NTayWR6clYgoWhhnyDwi/6zBNBUi+8tNf7df8cDnmVEBKxPSbHYDdXCnsasniCr1rgvIyCnniOeDTys0Gv+mtRz/oGT3Mn382EIbWwIFybQa7K16u66viiELAq49s64AruZVDQIP9d15IxrlFNjpLgKKdjPNBHkLv+Dqek7Zx5ijLW0TS7wCaJ85uQuxVuxXzJ20CO4Sb7+8pzlY8kcxLaklazBJtXOaVt/F9D/ozOTd7RodeFMynb8r7DI4wKQu4k0yajD4l5rhaC8No9j36An3+AtHs7KSoqW8mhR0isJ7QFQ4tw51YigR/wivXoDirGr/B4PA9QLzpw8PbJSLi3I96gLE9QMUrqn+36e9E9E3SnDZog3u2GTfLU9PYSU67m4UrV4dgTK7EItLJf2iBes6PxqQIcLTlI58drwAEhFHSt+q3xpgNN6GTdNr2Y6S4AtsNoiv62BJIE=
