language:
- python
python:
- '2.7'
install: ignore
script: ignore
before_deploy: cd nextbus_alexa
deploy:
- provider: lambda
  function_name: alexa-nextbus-dev
  region: us-east-1
  role: arn:aws:iam::251236465048:role/service-role/alexa-wmata
  runtime: python2.7
  module_name: nextbus
  handler_name: lambda_handler
  access_key_id: AKIAJ4RQKULZGZW6W6ZQ
  secret_access_key:
    secure: dNcskkQB4IkuGAMkPltgZgA7OKPZaha5l5t91xRA8IjHzafqH42F/AYa6PRb2yCdvL8zSq11yHmMcoLSiivrjgCwCn+BlmWvHBdhoTeJv9yNKGkrQuCyt8HS+j4bMeMyz55RPnoddEQvx2+ohKMCo9XBfD/bSBgobUy6VRI660GM9A4TjkfLNx5nH5+s5mBbyCXucQutmKhxQqSLWK1FYVCxlnH30Vin2ChjMXrAHSgR6RKn9JSYsl/2bAT7tJiMJyPrCHJWwxV45zQtBtVyyuYRw+8QPr3JuWP4JINTIOTFiuDuyy0or2kjCA+R3Tf1yRzofLrbIm+unjPRaEFw4VRSSUlDAABTScPEwucMYq9b2mLkamm9jLrMAFTmQA+jmc0gkvAO1EU+CZ4gorTlqlEQX63wPBjXVRYcndisOW0Y0UaqYyTvU1ZYENXzgK7T5TMiHUqOjmrTIiFNTz3X3MXeA1AxI3itoEA4qxGpaPnXqRM3/kcoMfgoaCCPQNe5CXo7g4wCnlHuZ8LDoorrXYo+f7EkD7XghX5uWdA2Fm1l5R/9iHnrzxXnhOW9AsQv6cA1wo/v8VWXNmnQBD9MYnTLMkBNYjgCvLCw79DcE6bHkvGJ7g/6EEbUBOjY0Bw05IuosWCkeCqTTw9X6zjgCPN2J822VJwv2gs/ichQ6nw=
  on:
    branch: develop
- provider: lambda
  function_name: alexa-nextbus-prod
  region: us-east-1
  role: arn:aws:iam::251236465048:role/service-role/alexa-wmata
  runtime: python2.7
  module_name: nextbus
  handler_name: lambda_handler
  access_key_id: AKIAJ4RQKULZGZW6W6ZQ
  secret_access_key:
    secure: dNcskkQB4IkuGAMkPltgZgA7OKPZaha5l5t91xRA8IjHzafqH42F/AYa6PRb2yCdvL8zSq11yHmMcoLSiivrjgCwCn+BlmWvHBdhoTeJv9yNKGkrQuCyt8HS+j4bMeMyz55RPnoddEQvx2+ohKMCo9XBfD/bSBgobUy6VRI660GM9A4TjkfLNx5nH5+s5mBbyCXucQutmKhxQqSLWK1FYVCxlnH30Vin2ChjMXrAHSgR6RKn9JSYsl/2bAT7tJiMJyPrCHJWwxV45zQtBtVyyuYRw+8QPr3JuWP4JINTIOTFiuDuyy0or2kjCA+R3Tf1yRzofLrbIm+unjPRaEFw4VRSSUlDAABTScPEwucMYq9b2mLkamm9jLrMAFTmQA+jmc0gkvAO1EU+CZ4gorTlqlEQX63wPBjXVRYcndisOW0Y0UaqYyTvU1ZYENXzgK7T5TMiHUqOjmrTIiFNTz3X3MXeA1AxI3itoEA4qxGpaPnXqRM3/kcoMfgoaCCPQNe5CXo7g4wCnlHuZ8LDoorrXYo+f7EkD7XghX5uWdA2Fm1l5R/9iHnrzxXnhOW9AsQv6cA1wo/v8VWXNmnQBD9MYnTLMkBNYjgCvLCw79DcE6bHkvGJ7g/6EEbUBOjY0Bw05IuosWCkeCqTTw9X6zjgCPN2J822VJwv2gs/ichQ6nw=
  on:
    branch: master
notifications:
  slack:
    rooms:
      secure: K93eIEhcJg1Rt5Rr9+wfaxwd7aajfpWNHy+s1FvG5xzsBpABQK0HQ45nu6FyMZlXixzKMIjVYECSJA8IHTuuYkK9Xh9I53dtkrihom2WQKHPP5Ick7r+1MIgFC1KdRLEEoDj5T+rtmk2UQMgQdJGH77GmY7+aKC5wS5oSZ9ukwpr03/6sRehTDRVv4rtz4wgRmgkcIAtfiZTclM4WRS2sDwpFM8NTTJqqWGAvM8sldwXlk20tubbL9aA3DajNiJ+nlD6gMsvljRZGPHFCLFrUAERxntF68HIaJwJbsvQqikKFdci82n8fChaMI3JYxBM6jqlGFsY/nDH7+6esIk/+wkZCSaDQCArpjBW5EpaCUSse8XI7ctNpiWn7zcFnZPTBLiBLY/dqv3HZ/FxMwng8U9tmqJFsKCXsm7pZQ6IO2MjRbl8e0WSS0kUWFPHcqJ3tbZrpOy9okYNZ1yokW3eREuVYVIuvZXb0U3Ohcs5a8r/WhccJkC0ML016R2VR1w6iJx8CtzY7Jrs0VWhZpzqqfff1F9scXXgbTtByXxfFHwBIEIRyRW1PZWVf0rycwkvf8/KrH5sGHabV05v5lotu6eBUYELVUsuNukh2Ur76Gg2vbOE4gaVKTUKirgPFyQ7rIJR6w+YCU1NhWyzflm0NGP9RkQN00jrWPudhmZdDHw=
