name: Deploy develop Lambda function

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy code to Lambda
        uses: denzalman/lambda-python-action@v1.1.0
        with:
          lambda_function_name: ${{ secrets.LAMBDA_FUNCTION_NAME_DEV }}
          lambda_region: ${{ secrets.LAMBDA_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
